package openstack

var (
	// nodeTypes all the Nodes that we support right now
	nodeTypes = map[string]struct{}{
		"openstack_compute_flavor_access_v2":                 struct{}{},
		"openstack_compute_flavor_v2":                        struct{}{},
		"openstack_compute_floatingip_associate_v2":          struct{}{},
		"openstack_compute_floatingip_v2":                    struct{}{},
		"openstack_compute_instance_v2":                      struct{}{},
		"openstack_compute_keypair_v2":                       struct{}{},
		"openstack_compute_quotaset_v2":                      struct{}{},
		"openstack_compute_secgroup_v2":                      struct{}{},
		"openstack_compute_servergroup_v2":                   struct{}{},
		"openstack_compute_volume_attach_v2":                 struct{}{},
		"openstack_containerinfra_cluster_v1":                struct{}{},
		"openstack_containerinfra_clustertemplate_v1":        struct{}{},
		"openstack_db_configuration_v1":                      struct{}{},
		"openstack_db_database_v1":                           struct{}{},
		"openstack_db_instance_v1":                           struct{}{},
		"openstack_db_user_v1":                               struct{}{},
		"openstack_dns_recordset_v2":                         struct{}{},
		"openstack_dns_zone_v2":                              struct{}{},
		"openstack_fw_firewall_v1":                           struct{}{},
		"openstack_fw_policy_v1":                             struct{}{},
		"openstack_fw_rule_v1":                               struct{}{},
		"openstack_identity_application_credential_v3":       struct{}{},
		"openstack_identity_endpoint_v3":                     struct{}{},
		"openstack_identity_project_v3":                      struct{}{},
		"openstack_identity_role_assignment_v3":              struct{}{},
		"openstack_identity_role_v3":                         struct{}{},
		"openstack_identity_service_v3":                      struct{}{},
		"openstack_identity_user_v3":                         struct{}{},
		"openstack_images_image_access_accept_v2":            struct{}{},
		"openstack_images_image_access_v2":                   struct{}{},
		"openstack_images_image_v2":                          struct{}{},
		"openstack_keymanager_container_v1":                  struct{}{},
		"openstack_keymanager_secret_v1":                     struct{}{},
		"openstack_lb_l7policy_v2":                           struct{}{},
		"openstack_lb_l7rule_v2":                             struct{}{},
		"openstack_lb_loadbalancer_v2":                       struct{}{},
		"openstack_lb_monitor_v1":                            struct{}{},
		"openstack_lb_monitor_v2":                            struct{}{},
		"openstack_lb_vip_v1":                                struct{}{},
		"openstack_networking_addressscope_v2":               struct{}{},
		"openstack_networking_floatingip_associate_v2":       struct{}{},
		"openstack_networking_floatingip_v2":                 struct{}{},
		"openstack_networking_network_v2":                    struct{}{},
		"openstack_networking_port_secgroup_associate_v2":    struct{}{},
		"openstack_networking_qos_bandwidth_limit_rule_v2":   struct{}{},
		"openstack_networking_qos_dscp_marking_rule_v2":      struct{}{},
		"openstack_networking_qos_minimum_bandwidth_rule_v2": struct{}{},
		"openstack_networking_qos_policy_v2":                 struct{}{},
		"openstack_networking_quota_v2":                      struct{}{},
		"openstack_networking_rbac_policy_v2":                struct{}{},
		"openstack_networking_router_interface_v2":           struct{}{},
		"openstack_networking_router_route_v2":               struct{}{},
		"openstack_networking_router_v2":                     struct{}{},
		"openstack_networking_subnet_route_v2":               struct{}{},
		"openstack_networking_subnet_v2":                     struct{}{},
		"openstack_networking_subnetpool_v2":                 struct{}{},
		"openstack_networking_trunk_v2":                      struct{}{},
		"openstack_objectstorage_container_v1":               struct{}{},
		"openstack_objectstorage_object_v1":                  struct{}{},
		"openstack_objectstorage_tempurl_v1":                 struct{}{},
		"openstack_orchestration_stack_v1":                   struct{}{},
		"openstack_sharedfilesystem_securityservice_v2":      struct{}{},
		"openstack_sharedfilesystem_share_access_v2":         struct{}{},
		"openstack_sharedfilesystem_share_v2":                struct{}{},
		"openstack_sharedfilesystem_sharenetwork_v2":         struct{}{},
		"openstack_vpnaas_endpoint_group_v2":                 struct{}{},
		"openstack_vpnaas_ike_policy_v2":                     struct{}{},
		"openstack_vpnaas_ipsec_policy_v2":                   struct{}{},
		"openstack_vpnaas_service_v2":                        struct{}{},
		"openstack_vpnaas_site_connection_v2":                struct{}{},
	}

	// edgeTypes map of all the supported Edges
	edgeTypes = map[string]struct{}{
		"openstack_compute_interface_attach_v2": struct{}{},
		"openstack_networking_port_v2":          struct{}{},
		"openstack_networking_secgroup_rule_v2": struct{}{},
		"openstack_networking_secgroup_v2":      struct{}{},
		"openstack_lb_listener_v2":              struct{}{},
		"openstack_lb_pool_v2":                  struct{}{},
		"openstack_lb_member_v2":                struct{}{},
	}
)
